### ISSUE TITLE
User Roles broken

### ISSUE THREAD

**Issue by jasonckeating** [PaloAltoNetworks/terraform-provider-prismacloud#85]
## Describe the bug

User Roles are creating plans as if the resource will be created, but the plugin crashes during `terraform apply`.

## Expected behavior

A user role should be created in Prisma

## Current behavior

```
╷
│ Error: Request cancelled
│ 
│   with prismacloud_user_role.this-admin["netapp"],
│   on accounts.tf line 27, in resource "prismacloud_user_role" "this-admin":
│   27: resource "prismacloud_user_role" "this-admin" {
│ 
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵

Stack trace from the terraform-provider-prismacloud_v1.1.4 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 72 [running]:
github.com/terraform-providers/terraform-provider-prismacloud/prismacloud.parseUserRole(0xc0003e51f0, 0xd1df9b)
	github.com/terraform-providers/terraform-provider-prismacloud/prismacloud/resource_user_role.go:140 +0x6c4
github.com/terraform-providers/terraform-provider-prismacloud/prismacloud.createUserRole(0xc0003e51f0, 0xf62a80, 0xc00058d2b0, 0x2, 0x19a39e0)
	github.com/terraform-providers/terraform-provider-prismacloud/prismacloud/resource_user_role.go:198 +0x5b
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0001635f0, 0xc000770640, 0xc0008843e0, 0xf62a80, 0xc00058d2b0, 0xec3a01, 0xc00058b1e8, 0xc00088a300)
	github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/resource.go:310 +0x365
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00015a100, 0xc000703a10, 0xc000770640, 0xc0008843e0, 0xc000883288, 0xc0007ccf90, 0xec55c0)
	github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e790, 0x126d540, 0xc00077e840, 0xc0003e4d20, 0xc00000e790, 0x0, 0xc0007d5b78)
	github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xfd0440, 0xc00000e790, 0x126d540, 0xc00077e840, 0xc000547920, 0x0, 0x126d540, 0xc00077e840, 0xc000880000, 0x29a)
	github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003bc780, 0x1277580, 0xc0003bd080, 0xc0007c0700, 0xc0003e9e60, 0x19695e0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
google.golang.org/grpc.(*Server).handleStream(0xc0003bc780, 0x1277580, 0xc0003bd080, 0xc0007c0700, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000363f0, 0xc0003bc780, 0x1277580, 0xc0003bd080, 0xc0007c0700)
	google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.27.1/server.go:720 +0xa1

Error: The terraform-provider-prismacloud_v1.1.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## Steps to reproduce

1. Create a user role
2. `terraform apply`

## Screenshots

![Screen Shot 2021-10-19 at 10 23 07 AM](https://user-images.githubusercontent.com/18508669/137941758-0a34851d-9987-4fd0-98d1-cc51c7d2d169.png)
![Screen Shot 2021-10-19 at 10 22 57 AM](https://user-images.githubusercontent.com/18508669/137941762-a9c2ef39-6b28-49d6-8c9d-d15505d2d7ed.png)

## Context

We are auto-building user roles for all accounts hooked up to Prisma.
This is preventing us from auto-provisioning these roles.

## Your Environment

- Version used:
  - terraform version 1.0.8
  - prisma provider version 1.1.4
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by ebeuerle** [comment]
Can you provide the entire TF file instead of just the error?

**Comment by sunkavillisuranya** [comment]
Hi @jasonckeating, this issue is solved in the pr 76 (https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/pull/76) When this PR is merged this issue will be solved, will get the pr merged soon. Thank you.

**Comment by jasonckeating** [comment]
Thanks, @sunkavillisuranya and @ebeuerle !

**Comment by jasonckeating** [comment]
@ebeuerle how soon until this can be reviewed / merged / new release?

**Comment by jasonckeating** [comment]
@ebeuerle can you cut a new release for us, so we can use the fix?

**Comment by ebeuerle** [comment]
Yes, it is going out today.  I was waiting on some last minute updates.
